### ISSUE TITLE
Forbidden Status Code 403

### ISSUE THREAD

**Issue by mbecker** [tim-hellhake/spotify-adapter#20]
Hi,

I've followed your instructions to create a Spotify App with Client ID and Client Secret, added the correct redirect URL and was then asked by the Add-on to open the following page:

```sh
https://ppacher.github.io/spotify-auth-callback/?code=XXXYYYZZZAiN94hJmNr05gli1ReGhbATwnF9jaAO_9_lz3C4Eqkl23N-7PREOCit23vxAl6zMRXVOKdG8sN6CqEzarL2-BTeHjr8q57uqB_ONq7M5NwNfO_umCC8_J4wMk4prTPTBIh7g5NGoP4d412aDuN6oIIMKoDm9QA_e61BiW2ky7oV7prj5RiFsTwIrl1Cw4ANy5QN4P2GNl97WPKK6EHPQDlbzXIwXp4ZgDnsJhKf56-TMljBBkxLSSYE9tp6rsICQHUo4nYOCkDHa9Gukcgxde165-JQ&state

(Updated the code)
```

The page shows an access token in an input field. Unfortunately the input filed is small and my first attempt was that I selected & copied only a part of the complete access token. However te access token is as follows:

```sh
XXXYYYZZZAiN94hJmNr05gli1ReGhbATwnF9jaAO_9_lz3C4Eqkl23N-7PREOCit23vxAl6zMRXVOKdG8sN6CqEzarL2-BTeHjr8q57uqB_ONq7M5NwNfO_umCC8_J4wMk4prTPTBIh7g5NGoP4d412aDuN6oIIMKoDm9QA_e61BiW2ky7oV7prj5RiFsTwIrl1Cw4ANy5QN4P2GNl97WPKK6EHPQDlbzXIwXp4ZgDnsJhKf56-TMljBBkxLSSYE9tp6rsICQHUo4nYOCkDHa9Gukcgxde165-JQ

(Updated the access token)

The number of characters for each access token is 292
```

After adding the access token in the Add-on settings and clicking save the following error occurs in the gateway logs:
```sh
2020-05-26 13:39:29.874 INFO   : spotify-adapter: Execute pause action
2020-05-26 13:39:29.999 INFO   : spotify-adapter: Unhandled Rejection
2020-05-26 13:39:30.000 ERROR  : spotify-adapter: { [WebapiError: Forbidden] name: 'WebapiError', message: 'Forbidden', statusCode: 403 }
```

Back in the seeting of the Add-on the access token is shorten as follows:
```sh
BQCSy8infA9XuexpcJ0pyxxx0JdNDzjPpxIwecONH8MLVRbHjg2B_UO7FKXD1TV7KIphcbx8GLsm7ClQhkMFnmZW_m7FPqQb2ufFwpkkoHyYBQ1lQXxMcBYqC1wyG5zfjqe6ZvnKzwS1Hdp_GoULM3gRlMH-

The number of characters for the shorten token is 156
Funny thing: The string is not part of the original access token
```

Any hints what I can check?

Thanks!

**Comment by tim-hellhake** [comment]
Hi Mats,

thanks for the note.

> Back in the seeting of the Add-on the access token is shorten as follows

That's actually intended 😄.
What you see in the callback URL is an authorization code.
The adapter uses the authorization code to fetch the access/refresh tokens.
After that the authorization code in the config is replaced by the access token.
That's why it looked like the token was truncated.

I just deleted my spotify app to test the whole process from the beginning.
Everything worked fine.
I'm not sure why you are getting the 403.

Can you please attach the logs after restarting the adapter?
Maybe the adapter is in the wrong state.

**Comment by tim-hellhake** [comment]
@mbecker any news on this?

**Comment by mbecker** [comment]
Hi @tim-hellhake, I‘m on vacation and haven’t yet the time to test it again. Will do that starting next week. Sorry for that and thanks again for your great work here!

**Comment by mbecker** [comment]
Hi @tim-hellhake ,

deleted and installed the add on again (the 'old' add on informations were loaded automatically from the gateway's DBs; interesting that the informations are not deleted by the gateway by uninstalling an add on). Now it's working! Great work! Thanks :-)

Have you updated anything?

**Comment by danielgallegosanchez** [comment]
Hi, Im having the same problem...
ERROR  : spotify-adapter: { [WebapiError: Forbidden] name: 'WebapiError', message: 'Forbidden', statusCode: 403 }
I've followed all the instructions and Im getting info about the spotify player but I can't send requests. 
Any idea?

**Comment by iamvdo** [comment]
Same for me (403 error as @danielgallegosanchez ) on fresh installation on this day. Any clue?

**Comment by tim-hellhake** [comment]
@danielgallegosanchez
Sorry, I didn't notice your comment because the issue was already closed.

@iamvdo
I'll try to reproduce it here with a fresh installation.

**Comment by tim-hellhake** [comment]
I couldn't reproduce the issue, but I found another one.
I rewrote the complete authorization process (#11 #15).
Instead of fiddling with URLs in the adapter config, there is now an extension.
If you open the menu, there should be a new `Spotify` entry.
You only need to paste your client id/secret there.
The rest of the process is now automated using redirects.

**Comment by tim-hellhake** [comment]
Just let me know if you had a chance to test the new update.

**Comment by TobiBu** [comment]
Hi Tim,

I saw the new update. The Spotify entry shows up in the menu as a separate entry. However, when I click on that there is no option to paste the client id or secret. I simply  get an empty blue screen.

**Comment by tim-hellhake** [comment]
Hi @TobiBu,

if you click on the Spotify entry you should see something like this:

![image](https://user-images.githubusercontent.com/17127122/104103511-c9dfd080-52a2-11eb-8e44-bac44eba7789.png)

What browser are you using?
Can you open the console in the dev tools to check if there are any js errors?
You can find info on how to open it in firefox/chrome here:
https://developer.mozilla.org/en-US/docs/Tools/Web_Console
https://developers.google.com/web/tools/chrome-devtools/open
https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by TobiBu** [comment]
Hi Tim,

so far I was using apple's safari. Now I've tried Chrome and firefox as well.

Google Chrome gives me the following message:

> Failed to load resource: the server responded with a status of 404 (Not Found)  spotify-adapter/api/status:1

> extension.js:54 Could not get status:  Error: 404 at api.js:45

and Firefox says the following:

> An element named "change-dialog-more-info" wasn't found in the source. overlay.js:185:16

> An element named "change-dialog-step-1-website" wasn't found in the source. overlay.js:185:16

> Could not get status:  Error: 404      extension.js:54:37       getJson api.js:45

maybe that helps.

**Comment by tim-hellhake** [comment]
> the server responded with a status of 404 (Not Found) spotify-adapter/api/status:1

One thing I noticed is that the error only mentions `spotify-adapter/api/status`.
You can check the request path in the network tab.
It should be `/extensions/spotify-adapter/api/status`.

Maybe there is an error in the backend which prevents the API handler from registering.
Can you please attach the debug logs after restarting the adapter to the issue?.
You can find them at `https://<your gateway>/settings/developer` under `View Internal Logs`.

**Comment by TobiBu** [comment]
Hi Tim,

so it seems the error occurs here:

> GET http://gateway.local/extensions/spotify-adapter/api/status

which causes a 404 error.

and the corresponding output in the log files say the following:

> 2021-01-10 12:10:59.247 INFO   : Loading add-on: spotify-adapter
2021-01-10 12:11:00.200 INFO   : spotify-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3
2021-01-10 12:11:00.231 INFO   : spotify-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-01-10 12:11:01.077 INFO   : spotify-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2021-01-10 12:11:02.478 INFO   : spotify-adapter: Loading add-on spotify-adapter from /home/pi/.webthings/addons/spotify-adapter
2021-01-10 12:11:02.679 INFO   : spotify-adapter: Loading token provider state
2021-01-10 12:11:02.686 INFO   : spotify-adapter: Refreshing access token
2021-01-10 12:11:02.915 INFO   : spotify-adapter: Unhandled Rejection
2021-01-10 12:11:02.918 ERROR  : spotify-adapter: { WebapiAuthenticationError: An authentication error occurred while communicating with Spotify's Web API.
2021-01-10 12:11:02.919 ERROR  : spotify-adapter: Details: invalid_client Failed to get client.
2021-01-10 12:11:02.920 ERROR  : spotify-adapter:     at _toError (/home/pi/.webthings/addons/spotify-adapter/node_modules/spotify-web-api-node/src/http-manager.js:43:12)
2021-01-10 12:11:02.921 ERROR  : spotify-adapter:     at /home/pi/.webthings/addons/spotify-adapter/node_modules/spotify-web-api-node/src/http-manager.js:71:25
2021-01-10 12:11:02.922 ERROR  : spotify-adapter:     at Request.callback (/home/pi/.webthings/addons/spotify-adapter/node_modules/superagent/lib/node/index.js:905:3)
2021-01-10 12:11:02.923 ERROR  : spotify-adapter:     at /home/pi/.webthings/addons/spotify-adapter/node_modules/superagent/lib/node/index.js:1127:20
2021-01-10 12:11:02.924 ERROR  : spotify-adapter:     at IncomingMessage.<anonymous> (/home/pi/.webthings/addons/spotify-adapter/node_modules/superagent/lib/node/parsers/json.js:22:7)
2021-01-10 12:11:02.924 ERROR  : spotify-adapter:     at Stream.emit (events.js:198:13)
2021-01-10 12:11:02.925 ERROR  : spotify-adapter:     at Unzip.<anonymous> (/home/pi/.webthings/addons/spotify-adapter/node_modules/superagent/lib/node/unzip.js:53:12)
2021-01-10 12:11:02.926 ERROR  : spotify-adapter:     at Unzip.emit (events.js:203:15)
2021-01-10 12:11:02.927 ERROR  : spotify-adapter:     at endReadableNT (_stream_readable.js:1145:12)
2021-01-10 12:11:02.928 ERROR  : spotify-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19)
2021-01-10 12:11:02.929 ERROR  : spotify-adapter:   body:
2021-01-10 12:11:02.930 ERROR  : spotify-adapter:    { error: 'invalid_client',
2021-01-10 12:11:02.931 ERROR  : spotify-adapter:      error_description: 'Failed to get client' },
2021-01-10 12:11:02.932 ERROR  : spotify-adapter:   headers:
2021-01-10 12:11:02.932 ERROR  : spotify-adapter:    { date: 'Sun, 10 Jan 2021 11:11:02 GMT',
2021-01-10 12:11:02.933 ERROR  : spotify-adapter:      'content-type': 'application/json',
2021-01-10 12:11:02.934 ERROR  : spotify-adapter:      'set-cookie':
2021-01-10 12:11:02.935 ERROR  : spotify-adapter:       [ '__Host-device_id=AQDxH83HemBzKjssAt-F23opz9fRhnb_MAS1NdmSu1_FkdwRhMH-ESTsdAPmLMGpnD7GJOV7HSFHt3feCZpmg5oGrF9IuGJRUQc;Version=1;Path=/;Max-Age=2147483647;Secure;HttpOnly;SameSite=Lax' ],
2021-01-10 12:11:02.936 ERROR  : spotify-adapter:      'sp-trace-id': 'b047c5960e831241',
2021-01-10 12:11:02.937 ERROR  : spotify-adapter:      'strict-transport-security': 'max-age=31536000',
2021-01-10 12:11:02.938 ERROR  : spotify-adapter:      'x-content-type-options': 'nosniff',
2021-01-10 12:11:02.939 ERROR  : spotify-adapter:      'content-encoding': 'gzip',
2021-01-10 12:11:02.940 ERROR  : spotify-adapter:      vary: 'Accept-Encoding',
2021-01-10 12:11:02.940 ERROR  : spotify-adapter:      server: 'envoy',
2021-01-10 12:11:02.941 ERROR  : spotify-adapter:      via: 'HTTP/2 edgeproxy, 1.1 google',
2021-01-10 12:11:02.942 ERROR  : spotify-adapter:      'alt-svc': 'clear',
2021-01-10 12:11:02.943 ERROR  : spotify-adapter:      connection: 'close',
2021-01-10 12:11:02.944 ERROR  : spotify-adapter:      'transfer-encoding': 'chunked' },
2021-01-10 12:11:02.945 ERROR  : spotify-adapter:   statusCode: 400 }

For me this looks quite cryptic, so any hint how to solve this would be useful.
thanks a lot.

**Comment by tim-hellhake** [comment]
Thank you for the detailed answer.
I think I found the issue.

> Refreshing access token

The adapter tries to refresh the access token after the start.
It looks like there is an invalid refresh token in your config from the previous version.
With the next update, you should be able to see the Spotify page.

**Comment by tim-hellhake** [comment]
Any news on this? :smile:

**Comment by TobiBu** [comment]
Sorry, I was quite busy...
Your update has solved the issue for me.
Thanks a lot
